name: faang

on:
  schedule:
    - cron: '0 8 * * 0'   # Every Sunday at 08:00 UTC
  workflow_dispatch: # This code allows to do manual runs.

jobs:
  faang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run your script
        run: echo "Hello from Sunday 8am workflow!"
