name: faang

on:
  schedule:
    - cron: '0 8 * * 0'   # Every Sunday at 08:00 UTC
  workflow_dispatch: # This codes allows to do manual runs.

jobs:
  faang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # o la versi√≥n de python que necesites

      - name: Install dependencies (if tienes requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run faang script
        run: python faang.py
